### PR TITLE
Add units to JSON spec

### PR DESCRIPTION
**Pull request by matthojo**

### CODE REVIEW

**Comment by tobli** [comment]
Cool. My original thinking was to have a separate schema/spec for the metrics/units. That way the workflow could be:
1. Have budget schema to specify the format of a budget file
2. Get a list of supported metrics (with a description and unit for each) from the tool that will produce the data to which the budget will be compared. E.g. something like
`sitespeed.io --budget-metrics > sitespeed-metrics.json`.
3. Based on the available metrics in the metrics file, construct a budget json that follows the budget schema. Given 1. and 2. there could be generic tooling that guides the user in creating a valid budget. E.g. allowing inputing 1MB for metrics that have a unit of bytes, but outputting that as 1048576 (bytes).

Benefits of that approach are:
- you can validate the metrics and units in your budget against the metrics your tools support
- no need to duplicate unit information in multiple budget files
- standardizing on "core representations" (ms for time, bytes for size etc.) removes logic from the budget validation step. Input/output using shorthand formats (e.g. GB, hours etc.) would be syntactic sugar in the tooling layer.

**Comment by tobli** [comment]
Adding one more schema would be added complexity, so it's definitely a tradeoff. Maybe we should prototype a number of options to get some more input.

**Comment by matthojo** [comment]
The major issue I see with a separate schema which is open to different formats, is that different formats could be any number of valid options, so enabling tools to choose would require there to be a potentially huge reference store to get appropriate translation. This doesn't factor in different short-hands like `s`, `sec`, `secs` etc.. This is with the thinking one configuration can be used by multiple tools.

I like idea of separating the two somehow and the more specifications the better so there is less ambiguity, I'm just wondering if there is a way we could incorporate the tools chosen method another way without introducing another document to manage.

**Comment by tobli** [comment]
I'd assumed tooling would primarily assist in building budgets given a specific tool, i.e. from a known set of metrics (built in or specified from an external file). At least initially, with enough adoption there might evolve some shared metric naming for multiple tools (e.g. all tools that collects wpt data).

Rather than a unit, a metric could be associated with a quantity. Absolute numbers, time and size (and possibly percentage) are the quantities I come to think of. In a (unitless) budget file these quantities would be expressed in a canonical unit (I suggest number, ms and bytes respectively). That way interoperability between tools is never an issue. At creation you can use a gui, natural language parsing etc, as long as you save in the canonical unit. Same thing in reverse for tools that visualise. One potential downside of this is that raw budget files might be harder to read to a human (e.g. recognising 1.2MB expressed as bytes. On the other hand you only need to learn the representation for time and size. It's entirely possible to create budget files by hand as well, the metrics file is merely a hint too humans and tools.

**Comment by matthojo** [comment]
I think sticking to number, ms and bytes would be a great suggestion, that way the visualisation of that data can be determined by the tool itself. Although slightly harder to consume for humans, having a single representation would be far easier to work with. Were you thinking of outlining this in the spec via something like;

```
{
"description": "The metric results unit of measurement",
 "type": "string",
"enum": [
   "bytes", "ms", "number"
]
}
```

**Comment by matthojo** [comment]
@tobli I've updated based on our discussion around limiting the unit types. Let me know what you think and I can merge in if all is good :)

**Comment by tobli** [comment]
👍

**Pull request merged**
